export function launchIncomeUI(c){
 const {S,$,api,esc,icon,notify,walletReady,needAccount}=c;
 let modalSequence=0;
 const art=t=>`<span class="lp-art">${t.logoURI?`<img src="${esc(t.logoURI)}" alt="" loading="lazy">`:icon('image')}</span>`;
 const num=(raw,d=6)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d===6?6:4}).format(Number(raw)/10**d);
 async function fees(){
  const actor=S.boot.me?.id;if(!actor||!S.boot.wallet||S.view!=='earnings')return;
  try{
   const data=await api('/api/launchpad/fees');if(actor!==S.boot.me?.id||S.view!=='earnings')return;S.launchFees=data;
   $('#lp-actual-claims')?.remove();$('.cr-earnings')?.insertAdjacentHTML('beforeend',`<section class="lp-profile-tokens lp-claims" id="lp-actual-claims"><div class="lp-section-title"><h3>Claim trading fees</h3><button class="r-text-button" data-action="lp-fees-refresh">Refresh</button></div>${data.claims.length?data.claims.map(t=>`<form class="lp-claim-row"><button type="button" data-action="nad-token" data-id="${esc(t.token)}">${art(t)}<span>${esc(t.name)}<small>${t.kind==='gift_claim'?'Beneficiary':'Creator'}</small></span></button><div class="lp-claim-amount"><b>${esc(t.amount)} ${esc(t.currency)}</b><button class="r-btn primary" type="button" data-action="lp-fee-claim" data-id="${esc(t.kind+':'+t.token)}" ${t.claimable?'':'disabled'}>Claim</button></div>${Number(t.pendingPoolFees)>0?`<small class="lp-pool-pending">Pool fees awaiting nad.fun settlement: ${esc(t.pendingPoolFees)} ${esc(t.currency)} · Threshold ${esc(t.settlementThreshold)}. Your settled balance is shown above.</small>`:''}<div class="r-form-error" role="alert"></div></form>`).join(''):'<p>No settled trading fees for this wallet.</p>'}<a href="${esc(data.verificationURL)}" target="_blank" rel="noopener noreferrer">Verify beneficiary on nad.fun ${icon('external')}</a>${data.errors.length?'<small>Some fee reads are unavailable. Refresh to try again.</small>':''}</section>`);
  }catch(e){if(S.view==='earnings'&&actor===S.boot.me?.id){$('#lp-fees-error')?.remove();$('.cr-earnings')?.insertAdjacentHTML('beforeend',`<p id="lp-fees-error">${esc(e.message)}</p>`);}}
 }
 async function claim(id,trigger){
  const item=S.launchFees?.claims.find(x=>x.kind+':'+x.token===id);if(!item?.claimable)return;
  const actor=S.boot.me?.id,form=trigger?.closest('form');trigger.disabled=true;
  try{if(!await walletReady()||actor!==S.boot.me?.id||!form?.isConnected)return;const p=await api('/api/execution/plan',{venue:'nadfees',kind:item.kind,token:item.token});if(actor!==S.boot.me?.id||!form.isConnected)return;await c.finance.review(p,trigger);}
  catch(e){if(form?.isConnected)$('.r-form-error',form).textContent=e.message;}
  finally{if(form?.isConnected&&!['submitted','unknown'].includes(form.dataset.orderState))trigger.disabled=false;}
 }
 async function revenue(token){return needAccount(async()=>{
  if(!await walletReady())return;const actor=S.boot.me.id,wallet=S.boot.wallet,request=++modalSequence;
  c.modal('Algorithm revenue','<div class="lp-income-loading" role="status">Loading revenue…</div>','lp-income-modal');
  try{
   const d=await api('/api/launchpad/revenue?token='+encodeURIComponent(token));if(actor!==S.boot.me?.id||wallet!==S.boot.wallet||request!==modalSequence||!$('.lp-income-modal'))return;
   const r=d.revenue;
   $('.lp-income-loading').outerHTML=`<form id="lp-revenue-form"><p class="lp-income-token">${esc(d.symbol)} on Monad</p>${r?`<div class="lp-income-balances"><div><small>Creator paid</small><b>${num(r.creatorPaid)} USDC</b></div><div><small>Buyback reserve</small><b>${num(r.pendingBuyback)} USDC</b></div><div><small>Tokens bought</small><b>${num(r.tokensBought,18)} ${esc(d.symbol)}</b></div><div><small>Sent to burn address</small><b>${num(r.tokensBurned,18)} ${esc(d.symbol)}</b></div></div>`:''}<div class="lp-income-controls"><label class="lp-field">Buyback share<input name="buyback" type="number" min="0" max="100" step="1" value="${r?r.buybackBps/100:20}" required></label><label class="lp-field">Burn share of tokens bought<input name="burn" type="number" min="0" max="100" step="1" value="${r?r.burnBps/100:100}" required></label><label class="lp-field">Slippage<input name="slippage" type="number" min="0.01" max="5" step="0.01" value="${r?r.slippageBps/100:1}" required></label><label class="lp-field">Max batch · USDC<input name="batch" type="number" min="0.01" max="1000" step="0.01" value="${r?Number(r.maxBatchRaw)/1e6:1}" required></label></div><div id="lp-revenue-limit" role="status">Checking price limit…</div><button class="r-text-button" type="button" id="lp-revenue-refresh">Refresh price limit</button><small class="lp-income-note">USDC → WMON → ${esc(d.symbol)}. A fixed minimum receive protects each buyback. When price exceeds that limit, reserves wait for your update. Tokens sent to the burn address remain in total supply.</small><div class="r-form-error" role="alert"></div><button class="lp-primary full" type="submit" disabled>${r?'Update allocation':'Activate revenue vault'}</button>${!r?'<small class="lp-income-note">Deploys your own vault. No liquidity deposit. Network fee cap: 0.3 MON.</small>':''}</form>${r?`<form id="lp-revenue-bind"><label class="lp-field">Algorithm<select name="feed" required><option value="">Choose an algorithm</option>${d.feeds.map(f=>`<option value="${esc(f.id)}">${esc(f.name)}${d.boundFeeds.includes(f.id)?' · Connected':''}</option>`).join('')}</select></label><small>New purchases use this allocation. Existing invoices keep their original terms.</small><div class="r-form-error" role="alert"></div><button class="lp-secondary full" type="submit" ${d.feeds.length?'':'disabled'}>Connect algorithm</button></form><form class="lp-income-actions"><button type="button" class="lp-secondary" data-action="lp-revenue-pause" data-id="${esc(token)}" data-paused="${r.paused?'false':'true'}">${r.paused?'Resume buybacks':'Pause buybacks'}</button><button type="button" class="lp-secondary" data-action="lp-revenue-checkpoint" data-id="${esc(token)}">Refresh oracle</button><button class="lp-secondary" type="button" data-action="lp-revenue-execute" data-id="${esc(token)}">Run buyback</button><div class="r-form-error" role="alert"></div></form><a href="/?view=activity" data-nav="activity">View transactions</a>`:''}`;
   const form=$('#lp-revenue-form'),button=$('[type=submit]',form);let serial=0,quote=null,timer;
   const values=()=>({token,buybackBps:Number(form.elements.buyback.value)*100,burnBps:Number(form.elements.burn.value)*100,slippageBps:Math.round(Number(form.elements.slippage.value)*100),maxBatchUSDC:form.elements.batch.value});
   const current=()=>form.isConnected&&actor===S.boot.me?.id&&wallet===S.boot.wallet;
   async function price(){const seq=++serial;button.disabled=true;quote=null;try{const fields=values(),p=await api('/api/launchpad/revenue/limits',fields);if(!current()||seq!==serial)return;quote={...p,signature:JSON.stringify(fields)};$('#lp-revenue-limit').textContent='Minimum '+p.minimumTokensPerUSDC+' '+d.symbol+' per USDC';button.disabled=false;}catch(e){if(current()&&seq===serial){$('#lp-revenue-limit').textContent=e.message;}}}
   form.oninput=()=>{if(form.dataset.pending==='true')return;serial++;button.disabled=true;clearTimeout(timer);timer=setTimeout(price,250);};$('#lp-revenue-refresh').onclick=()=>{if(form.dataset.pending!=='true')price();};await price();
   form.onsubmit=async e=>{e.preventDefault();if(S.financialBusy||form.dataset.pending==='true'||['submitted','unknown'].includes(form.dataset.orderState))return;button.disabled=true;form.dataset.pending='true';
    try{if(!current()||!quote||quote.expires<=Date.now()/1000||quote.signature!==JSON.stringify(values()))throw Error('Refresh the price limit before continuing');const fields=values(),p=await api('/api/execution/plan',{venue:'nadrevenue',kind:r?'revenue_policy':'revenue_deploy',...fields,minTokensPerUSDC:quote.minTokensPerUSDC});if(!current()||JSON.stringify(fields)!==JSON.stringify(values()))return;if(p.summary.minTokensPerUSDC!==quote.minTokensPerUSDC)throw Error('Price limit changed. Refresh it before signing.');delete form.dataset.pending;await c.finance.review(p,button);}catch(e){if(current())$('.r-form-error',form).textContent=e.message;}finally{delete form.dataset.pending;if(current()&&!['submitted','unknown'].includes(form.dataset.orderState))button.disabled=false;}
   };
   const bind=$('#lp-revenue-bind');if(bind)bind.onsubmit=async e=>{e.preventDefault();const b=$('[type=submit]',bind);b.disabled=true;try{await api('/api/launchpad/revenue/bind',{token,feed:bind.elements.feed.value});if(bind.isConnected&&actor===S.boot.me?.id){notify('Algorithm connected');c.closeModal();await c.boot();}}catch(e){if(bind.isConnected)$('.r-form-error',bind).textContent=e.message;}finally{if(b.isConnected)b.disabled=false;}};
  }catch(e){if(actor===S.boot.me?.id&&request===modalSequence&&$('.lp-income-loading'))$('.lp-income-loading').textContent=e.message;}
 });}
 async function action(kind,token,trigger){if(!trigger||S.financialBusy)return;const actor=S.boot.me?.id;trigger.disabled=true;try{if(!await walletReady()||actor!==S.boot.me?.id)return;const p=await api('/api/execution/plan',{venue:'nadrevenue',kind,token,...(kind==='revenue_pause'?{paused:trigger.dataset.paused==='true'}:{})});if(trigger.isConnected&&actor===S.boot.me?.id)await c.finance.review(p,trigger);}catch(e){notify(e.message);}finally{if(trigger.isConnected&&!['submitted','unknown'].includes(trigger.closest('form')?.dataset.orderState))trigger.disabled=false;}}
 async function handle(name,id,trigger){
  if(name==='lp-fee-claim'){await claim(id,trigger);return true;}
  if(name==='lp-fees-refresh'){if(S.boot.wallet)await api('/api/launchpad/fees?refresh=1');await fees();return true;}
  if(name==='lp-revenue'){await revenue(id);return true;}
  if(name==='lp-revenue-pause'){await action('revenue_pause',id,trigger);return true;}
  if(name==='lp-revenue-checkpoint'||name==='lp-revenue-execute'){await action(name==='lp-revenue-checkpoint'?'revenue_checkpoint':'revenue_execute',id,trigger);return true;}
  return false;
 }
 return {fees,handle};
}
