export function socialLoopUI(c){
 const {S,$,api,esc,icon,usd,pct,age,modal,closeModal,notify,needAccount,navigate,render,boot,avatar}=c;
 const price=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumSignificantDigits:6}).format(Number(v)):'—';
 function card(p){
  const sig=p.signal,fill=p.verifiedTrade;
  if(sig){const t=sig.terms,change=sig.priceChangePercent;return `<section class="rl-signal" aria-label="Verified price signal"><header><span class="rl-kicker">${t.direction==='up'?'Upside':'Downside'} signal</span><span class="rl-state ${sig.state==='invalidated'?'negative':''}">${esc(sig.state.replaceAll('_',' '))}</span></header><div class="rl-signal-price"><strong>${price(sig.latest.price)}</strong><span class="${change>=0?'positive':'negative'}">${pct(change)}</span></div><dl class="rl-values"><div><dt>At publication</dt><dd>${price(sig.entry.price)}</dd></div><div><dt>Target</dt><dd>${price(t.target)}</dd></div><div><dt>Invalidation</dt><dd>${price(t.invalidation)}</dd></div></dl><footer><span>${esc(sig.entry.source)} · ${esc(age(sig.entry.observedAt))}${sig.stale?' · Price stale':''}</span><button data-action="signal-details" data-id="${esc(p.id)}">Details ${icon('chevron')}</button></footer></section>`;}
  if(fill)return `<section class="rl-fill"><header><span class="rl-kicker">Verified fill</span><span class="rl-state">Finalized</span></header><div class="rl-fill-main"><span><strong>${esc(fill.label||(fill.side==='buy'?'Bought':'Sold'))} ${esc(fill.quantity)} ${esc(fill.symbol)}</strong><small>${esc(fill.venue)} · ${esc(age(fill.created))}</small></span><button class="r-btn rl-buy" data-action="${fill.kind==='perps'?'perpl-order':'trade'}" data-id="${esc(fill.kind==='perps'?fill.marketId:fill.asset)}">${fill.kind==='perps'?'Trade':'Buy'}</button></div><a href="https://monadvision.com/tx/${esc(fill.tx)}" target="_blank" rel="noopener noreferrer">View receipt ${icon('external')}</a>${p.author.id===S.boot.me?.id?`<button class="r-text-button" data-action="fill-withdraw" data-id="${esc(p.id)}">Stop sharing</button>`:''}</section>`;
  return '';
 }
 function fields(){return `<details class="rl-signal-form"><summary>${icon('chart')}Add a signal</summary><p class="r-muted">The current price and publication time are recorded by Rally.</p><label class="rl-check"><input type="checkbox" name="signalEnabled">Publish a price signal</label><div class="rl-form-grid"><label class="r-field">Direction<select name="signalDirection"><option value="up">Upside</option><option value="down">Downside</option></select></label><label class="r-field">Duration<select name="signalHours"><option value="24">24 hours</option><option value="168">7 days</option><option value="720">30 days</option></select></label><label class="r-field">Target · USD<input type="number" name="signalTarget" min="0" step="any" inputmode="decimal"></label><label class="r-field">Invalidation · USD<input type="number" name="signalStop" min="0" step="any" inputmode="decimal"></label></div></details>`;}
 function pack(form,data){if(form.elements.signalEnabled?.checked)data.signal={direction:form.elements.signalDirection.value,hours:Number(form.elements.signalHours.value),target:form.elements.signalTarget.value,invalidation:form.elements.signalStop.value};for(const k of Object.keys(data))if(k.startsWith('signal')&&k!=='signal')delete data[k];return data;}
 async function settings(){needAccount(async()=>{
  const d=await api('/api/push/settings');modal('Notifications',`<div class="rl-settings"><p>Posts, price alerts and token migrations.</p><div class="rl-setting-row"><span><b>This browser</b><small>${!('PushManager' in window)?'Push is unavailable in this browser':Notification.permission==='denied'?'Enable notifications in browser settings':d.enabled?'Notifications enabled':'Notifications off'}</small></span><button class="r-btn primary" id="rl-push-toggle">${d.enabled?'Turn off':'Enable'}</button></div><fieldset class="rl-options"><legend>Notify me about</legend>${[['social','Replies and follows'],['algorithm','Subscribed algorithms'],['price','Watched-token prices'],['migration','DEX migrations'],['signal','Saved signals'],['trade','Shared trades']].map(([id,label])=>`<label class="rl-check"><input type="checkbox" name="push-kind" value="${id}" ${d.kinds.includes(id)?'checked':''}>${label}</label>`).join('')}</fieldset><button class="r-btn" data-action="market-alert-settings">Manage price alerts</button><p class="r-form-error" id="rl-push-error" role="alert"></p><small class="r-muted">Android lock-screen alerts become available after Firebase is configured.</small></div>`);
  $('#rl-push-toggle').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{
   if(d.enabled){await api('/api/push/settings',{enabled:false,kinds:d.kinds});await detach();}
   else{if(!('PushManager' in window)||!('serviceWorker' in navigator))throw Error('This browser does not support push notifications');if(await Notification.requestPermission()!=='granted')throw Error('Notifications are not allowed');const reg=await navigator.serviceWorker.register('/rally-offline.js',{scope:'/'});await navigator.serviceWorker.ready;const key=Uint8Array.from(atob(d.config.applicationServerKey.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-d.config.applicationServerKey.length%4)%4)),ch=>ch.charCodeAt(0));const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});const device=await api('/api/push/register',{kind:'web',subscription:sub.toJSON()});localStorage.setItem('rally:push-device',JSON.stringify({id:device.id,owner:S.boot.me.id}));await api('/api/push/settings',{enabled:true,kinds:[...document.querySelectorAll('[name=push-kind]:checked')].map(x=>x.value)});}
   await settings();
  }catch(error){$('#rl-push-error').textContent=error.message;b.disabled=false;}};
  document.querySelectorAll('[name=push-kind]').forEach(el=>el.onchange=async()=>{if(d.enabled)try{await api('/api/push/settings',{enabled:true,kinds:[...document.querySelectorAll('[name=push-kind]:checked')].map(x=>x.value)});}catch(error){notify(error.message);}});
 });}
 async function detach(){let device;try{device=JSON.parse(localStorage.getItem('rally:push-device')||'null');}catch{}if(device?.owner===S.boot.me?.id)await api('/api/push/remove',{id:device.id});if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration('/');const sub=await reg?.pushManager?.getSubscription();if(sub)await sub.unsubscribe();}localStorage.removeItem('rally:push-device');}
 async function alerts(){needAccount(async()=>{const d=await api('/api/market-alerts');modal('Price alerts',`<div class="rl-alerts">${S.boot.watches.map(id=>{const a=d.alerts.find(x=>x.asset===id),token=c.token(id);return `<label class="rl-setting-row"><span><b>${esc(token?.symbol||id.slice(0,8))}</b><small>Price moves and finalized DEX migrations</small></span><input type="checkbox" data-alert="${esc(id)}" ${a?.enabled?'checked':''} aria-label="Alert for ${esc(token?.symbol||id)}"></label>`;}).join('')||'<p>Add a token to your watchlist first.</p>'}<p class="r-muted">5% price changes, at most once every five minutes per token.</p></div>`);document.querySelectorAll('[data-alert]').forEach(el=>el.onchange=async()=>{el.disabled=true;try{await api('/api/market-alerts',{asset:el.dataset.alert,enabled:el.checked,thresholdBps:500});}catch(error){el.checked=!el.checked;notify(error.message);}finally{el.disabled=false;}});});}
 async function share(){needAccount(async()=>{const d=await api('/api/trades/shareable');modal('Share a trade',`<div class="rl-share-list">${d.trades.map(t=>`<article class="rl-share-row"><span><b>${esc(t.side==='buy'?'Bought':'Sold')} ${esc(t.quantity)} ${esc(t.symbol)}</b><small>${esc(t.venue)} · Finalized · ${esc(age(t.created))}</small></span>${t.sharedPost?'<span class="r-muted">'+(t.withdrawn?'Withdrawn':'Shared')+'</span>':`<button class="r-btn" data-action="fill-publish" data-id="${esc(t.id)}">Share</button>`}</article>`).join('')||'<p>No finalized token fills to share yet.</p>'}<p class="r-muted">Only trades you choose are published. Followers choose their own amount.</p></div>`);});}
 async function benefits(owner){const d=await api('/api/benefits?owner='+encodeURIComponent(owner));modal('Community benefits',`<div class="rl-benefits"><p class="r-muted">${d.token?'Hold the community token to unlock benefits.':'No token benefits configured yet.'}</p>${d.tiers.map(t=>`<article class="rl-tier ${d.tier?.label===t.label?'is-qualified':''}"><span><b>${esc(t.label)}</b><small>Hold ${esc(t.minimum)} tokens${t.discountBps?' · '+t.discountBps/100+'% off algorithms':''}</small><small>${t.feeds.length} feeds included</small></span>${d.tier?.label===t.label?icon('check'):''}</article>`).join('')}${S.boot.me&&d.token?`<button class="r-btn primary full" data-action="benefits-refresh" data-id="${esc(owner)}">${d.verified?'Refresh holdings':'Check my holdings'}</button>${d.verified?`<small class="r-muted">Finalized block ${d.observedBlock} · ${esc(age(d.expires-120))}</small><label class="rl-check"><input id="rl-member-badge" type="checkbox" ${d.showBadge?'checked':''}>Show my member badge</label>`:''}`:''}${d.editable?`<button class="r-btn full" data-action="benefits-edit" data-id="${esc(owner)}">Set benefits</button>`:''}</div>`);if($('#rl-member-badge'))$('#rl-member-badge').onchange=async e=>{try{await api('/api/benefits/badge',{owner,enabled:e.target.checked});}catch(error){notify(error.message);}};}
 async function editBenefits(owner){const d=await api('/api/benefits?owner='+encodeURIComponent(owner));const feeds=S.boot.feeds.filter(f=>f.owner===S.boot.me?.id);if(!d.editable)throw Error('Only the creator can edit benefits');let tiers=d.tiers.length?d.tiers:[{label:'Member',minimum:'100',discountBps:1000,feeds:[]}];
 const paint=()=>{modal('Set benefits',`<form id="rl-benefits-form"><div id="rl-tiers">${tiers.map((t,i)=>`<fieldset class="rl-tier-form"><legend>Tier ${i+1}</legend><div class="rl-form-grid"><label class="r-field">Name<input name="label-${i}" value="${esc(t.label)}" maxlength="28" required></label><label class="r-field">Minimum tokens<input name="minimum-${i}" value="${esc(t.minimum)}" type="number" step="any" min="0" required></label><label class="r-field">Algorithm discount · %<input name="discount-${i}" value="${t.discountBps/100}" type="number" min="0" max="90" step="1"></label></div><div class="rl-options">${feeds.map(f=>`<label class="rl-check"><input name="unlock-${i}" type="checkbox" value="${esc(f.id)}" ${t.feeds.includes(f.id)?'checked':''}>Include ${esc(f.name)}</label>`).join('')}</div></fieldset>`).join('')}</div><button type="button" class="r-text-button" id="rl-add-tier" ${tiers.length>=5?'disabled':''}>Add tier</button><fieldset class="rl-options"><legend>Require holdings or subscription</legend>${feeds.map(f=>`<label class="rl-check"><input name="gate" type="checkbox" value="${esc(f.id)}" ${d.gatedFeeds.includes(f.id)?'checked':''}>${esc(f.name)}</label>`).join('')}</fieldset><p class="r-form-error" role="alert"></p><button class="r-btn primary full" type="submit">Save benefits</button></form>`);
 const read=()=>tiers.map((_,i)=>({label:$(`[name=label-${i}]`).value,minimum:$(`[name=minimum-${i}]`).value,discountBps:Math.round(Number($(`[name=discount-${i}]`).value)*100),feeds:[...document.querySelectorAll(`[name=unlock-${i}]:checked`)].map(x=>x.value)}));
 $('#rl-add-tier').onclick=()=>{tiers=read();d.gatedFeeds=[...document.querySelectorAll('[name=gate]:checked')].map(x=>x.value);tiers.push({label:'',minimum:'',discountBps:0,feeds:[]});paint();};$('#rl-benefits-form').onsubmit=async e=>{e.preventDefault();const b=$('[type=submit]',e.currentTarget);b.disabled=true;try{await api('/api/benefits/save',{tiers:read(),gatedFeeds:[...document.querySelectorAll('[name=gate]:checked')].map(x=>x.value)});await boot();await benefits(owner);}catch(error){$('.r-form-error',e.currentTarget).textContent=error.message;b.disabled=false;}};};paint();}
 async function league(){const d=await api('/api/league');const own=S.boot.feeds.filter(f=>f.owner===S.boot.me?.id&&f.algorithm_version);modal('Weekly league',`<div class="rl-league"><header><b>${new Date(d.starts*1000).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})} — ${new Date((d.ends-1)*1000).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})}</b><small>UTC · 24h price discovery</small></header>${own.length?`<div class="rl-enroll"><select id="rl-enroll-feed" aria-label="Your algorithm">${own.map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('')}</select><button class="r-btn" data-action="league-enroll">Enter</button></div>`:''}${d.entries.map(e=>`<article class="rl-league-row"><span class="rl-rank">${e.rank||'—'}</span>${avatar(e.author)}<span><b>${esc(e.name)}</b><small>@${esc(e.author.handle)} · ${e.samples} measured · ${e.pending} pending</small><small>${e.discoveryDelaySeconds==null?'—':Math.round(e.discoveryDelaySeconds/60)+'m'} post-to-pick · ${e.reader.engagementRate==null?'—':e.reader.engagementRate+'%'} engagement · ${e.performance.roi==null?'No closed trades':pct(e.performance.roi)+' realized ROI'}</small></span><strong class="${e.priceChangePercent>=0?'positive':'negative'}">${e.priceChangePercent==null?'—':pct(e.priceChangePercent)}</strong></article>`).join('')||'<div class="rl-empty">No entries yet. Publish a custom algorithm to join.</div>'}<p class="r-muted">${esc(d.method)}</p><p class="r-muted">Price movement is not realized profit. Three measured samples to rank.</p><details><summary>Candidate snapshots</summary>${d.rounds.map(r=>`<p class="rl-hash">${esc(age(r.created))} · ${esc(r.digest)}</p>`).join('')||'<p>No hourly rounds captured yet.</p>'}</details></div>`,'r-wide-modal');}
 async function record(owner){const d=await api('/api/signals?owner='+encodeURIComponent(owner));modal('Signal record',`<div class="rl-record"><dl class="rl-values"><div><dt>Target reached</dt><dd>${d.counts.target_reached}</dd></div><div><dt>Invalidated</dt><dd>${d.counts.invalidated}</dd></div><div><dt>Expired</dt><dd>${d.counts.expired}</dd></div></dl><p class="r-muted">${d.withdrawn} withdrawn · ${d.counts.active} active. Deleted calls remain in counts.</p>${d.signals.map(x=>`<button class="rl-record-row" data-action="open-post" data-id="${esc(x.post)}"><b>${esc(x.entry.symbol)}</b><span>${esc(x.state.replaceAll('_',' '))}</span><span>${pct(x.priceChangePercent)}</span></button>`).join('')}<p class="r-muted">Observed prices, not executed trade returns.</p></div>`);}
 async function handle(action,id,el){
  if(action==='push-settings'){await settings();return true;}if(action==='market-alert-settings'){await alerts();return true;}if(action==='share-fill'){await share();return true;}
  if(action==='fill-publish'){el.disabled=true;try{const p=await api('/api/trades/share',{trade:id});closeModal();S.post=p.id;await navigate('post');}catch(e){el.disabled=false;throw e;}return true;}
  if(action==='fill-withdraw'){await api('/api/trades/withdraw',{post:id});closeModal();await render();return true;}
  if(action==='signal-record'){await record(id);return true;}
  if(action==='signal-details'){const p=await api('/api/post?id='+encodeURIComponent(id));modal('Signal',card(p)+`<p class="r-muted">Recorded ${new Date(p.signal.entry.observedAt*1000).toLocaleString()}. Ends ${new Date(p.signal.expires*1000).toLocaleString()}. Crossings are recorded when a fresh price is observed.</p>`);return true;}
  if(action==='benefits-open'){await benefits(id);return true;}if(action==='benefits-edit'){await editBenefits(id);return true;}if(action==='benefits-refresh'){el.disabled=true;try{await api('/api/benefits/refresh',{owner:id});await boot();await benefits(id);}catch(e){el.disabled=false;throw e;}return true;}
  if(action==='weekly-league'){await league();return true;}if(action==='league-enroll'){el.disabled=true;try{await api('/api/league/enroll',{feed:$('#rl-enroll-feed').value});await league();}catch(e){el.disabled=false;throw e;}return true;}
  return false;
 }
 return {card,fields,pack,handle,detach};
}
