// Wallet snapshots render independently of market discovery and order history.
export function walletUI(c){
 const {S,$,api,esc,icon,usd,pct,age,modal,notify,pageHeader,empty,logo}=c;
 let request;const qrCache=new Map();
 const identity=()=>`${S.boot.me?.id||''}:${S.boot.wallet||''}`;
 function remember(p){if(p.wallet?.toLowerCase()!==S.boot.wallet?.toLowerCase())return false;S.portfolio=p;for(const h of p.holdings||[]){if(h.token){const i=S.tokens.findIndex(t=>t.id===h.asset);if(i<0)S.tokens.push(h.token);else S.tokens[i]={...S.tokens[i],...h.token};}}return true;}
 const cached=()=>S.portfolio?.wallet?.toLowerCase()===S.boot.wallet?.toLowerCase()?S.portfolio:null;
 function fitSheet(){
  const instance=S.modal,overlay=$('.r-wallet-modal')?.closest('.r-overlay'),viewport=window.visualViewport;if(!viewport||!overlay)return;
  let frame;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(S.modal!==instance)return;overlay.style.height=viewport.height+'px';overlay.style.top=viewport.offsetTop+'px';overlay.style.bottom='auto';overlay.style.setProperty('--wallet-visible-height',viewport.height+'px');});};
  viewport.addEventListener('resize',update);viewport.addEventListener('scroll',update);update();
  const cleanup=instance.cleanup;instance.cleanup=()=>{cleanup?.();cancelAnimationFrame(frame);viewport.removeEventListener('resize',update);viewport.removeEventListener('scroll',update);};
 }
 async function snapshot(){const owner=identity();if(request?.owner===owner)return request.promise;const promise=api('/api/portfolio').then(p=>{if(owner===identity())remember(p);return p;}).finally(()=>{if(request?.promise===promise)request=null;});request={owner,promise};return promise;}
 function hero(p){return `<section class="r-wallet-hero" aria-label="Wallet balance"><small data-balance-label>Wallet balance · USD</small><h2 data-balance-value>${p?.valuation?.valueUSD!=null?usd(p.valuation.valueUSD):'—'}</h2><div class="r-wallet-change" data-balance-change aria-live="polite"></div><div class="r-wallet-actions"><button class="r-btn primary" data-action="wallet-send">${icon('send')}Send</button><button class="r-btn" data-action="wallet-deposit">${icon('plus')}Deposit</button></div><small data-balance-note hidden></small></section>`;}
 function paintHero(host,p){
  const v=p?.valuation,change=v?.change24hPercent,value=v?.valueUSD!=null?usd(v.valueUSD):'—',number=host.querySelector('[data-balance-value]');
  host.querySelector('[data-balance-label]').textContent=(v?.partial?'Priced balance':'Wallet balance')+' · USD';
  if(number.textContent!==value){number.textContent=value;if(!matchMedia('(prefers-reduced-motion:reduce)').matches)number.animate([{opacity:.5,transform:'translateY(3px)'},{opacity:1,transform:'none'}],{duration:180,easing:'cubic-bezier(.22,.8,.24,1)'});}
  const label=host.querySelector('[data-balance-change]');label.className='r-wallet-change '+(change==null?'':Number(change)>=0?'positive':'negative');
  const text=change!=null?pct(change)+' <span>24h price change</span>':!p||p.refreshing?'Updating balances…':'24h price change unavailable';if(label.innerHTML!==text)label.innerHTML=text;
  const note=host.querySelector('[data-balance-note]');note.textContent=v?.unpricedAssets?`${v.unpricedAssets} asset${v.unpricedAssets===1?'':'s'} without a current price`:p?.error?'Last known balances · Refreshing':p?.unavailable?.length?'Some balances are temporarily unavailable':'';note.hidden=!note.textContent;
 }
 async function profile(){const host=$('#profile-balance');if(!host||!S.boot.wallet)return;const owner=identity();host.innerHTML=hero(cached());paintHero(host,cached());for(let i=0;i<12&&host.isConnected&&owner===identity();i++){try{const p=await snapshot();if(!host.isConnected||owner!==identity())return;paintHero(host,p);if(!p.refreshing)return;}catch{return;}await new Promise(r=>setTimeout(r,i?1500:350));}}
 function holdings(p){return `<div class="r-wallet-holdings">${(p.holdings||[]).filter(h=>Number(h.amount)>0).map(h=>{const t=h.token||c.token(h.asset);return `<button class="r-wallet-holding" data-action="${t?.nadfun?'nad-token':'market-detail'}" data-id="${esc(h.asset)}">${logo(t)}<span><b>${esc(t?.symbol||h.asset)}</b><small>${esc(Number(h.amount).toLocaleString('en-US',{maximumSignificantDigits:8}))} ${esc(t?.symbol||'')}${h.staleBalance?' · Last known':''}</small></span><b>${h.valueUSD!=null?usd(h.valueUSD):'—'}</b></button>`;}).join('')||`<p class="r-note">${p.refreshing?'Checking your assets…':p.complete?'No token balances yet.':'Balances are temporarily unavailable.'}</p>`}</div><div class="r-data-foot">${p.refreshing?'Updating…':p.unavailable?.length?'Some token balances are unavailable':'On-chain wallet balances'}${p.fetchedAt?' · '+age(p.fetchedAt):''}</div>`;}
 async function render(seq){
  $('#page').innerHTML=pageHeader('Portfolio')+(S.boot.wallet?`<div id="wallet-summary">${hero(cached())}<div id="wallet-holdings">${cached()?holdings(cached()):'<div class="r-wallet-skeleton" aria-label="Loading balances"><i></i><i></i><i></i></div>'}</div></div><div class="r-subhead"><h2>Recent swaps</h2></div><div id="wallet-orders"></div>`:empty('Connect your wallet','','<button class="r-btn primary" data-action="wallet">Connect wallet</button>'));
  if(!S.boot.wallet)return;const host=$('#wallet-summary'),owner=identity();paintHero(host,cached());let previous;
  api('/api/orders').then(o=>{if(!host.isConnected||owner!==identity())return;$('#wallet-orders').innerHTML=o.orders.slice(0,10).map(x=>`<div class="r-order-row"><span>Spot swap <small>${age(x.created)}</small></span><span class="r-pill">${esc(x.state)}</span><a href="https://monadvision.com/tx/${esc(x.tx)}" target="_blank" rel="noopener noreferrer">View ${icon('external')}</a></div>`).join('')||'<p class="r-note">Your swaps appear here.</p>';}).catch(()=>{});
  for(let i=0;i<12&&host.isConnected&&owner===identity();i++){try{const p=await snapshot();if(!host.isConnected||owner!==identity())return;paintHero(host,p);const html=holdings(p);if(html!==previous){$('#wallet-holdings').innerHTML=html;previous=html;}if(!p.refreshing)return;}catch{if(host.isConnected&&!cached())$('#wallet-holdings').innerHTML='<p class="r-note">Balances are temporarily unavailable. Try refreshing.</p>';return;}await new Promise(r=>setTimeout(r,i?1500:350));}
 }
 async function deposit(){
  if(!S.boot.wallet){c.connect();return;}const wallet=S.boot.wallet,owner=identity(),key=wallet.toLowerCase();
  modal('Deposit',`<div id="wallet-deposit" class="r-deposit"><span class="r-wallet-network"><img src="/assets/MON.png" width="18" height="18" alt="">Monad</span><div class="r-qr-frame" aria-busy="${!qrCache.has(key)}">${qrCache.has(key)?`<img class="r-deposit-qr" src="${esc(qrCache.get(key))}" width="208" height="208" alt="Wallet address QR code">`:'<span class="r-qr-placeholder" role="status">Preparing QR…</span>'}</div><p>Send assets on Monad to this address.</p><div class="r-wallet-address">${esc(wallet)}</div><small class="r-qr-error" role="status"></small></div><div class="r-wallet-footer"><button class="r-btn primary full" id="copy-wallet-address">${icon('copy')}Copy address</button></div>`,'r-wallet-modal r-deposit-modal');
  fitSheet();const host=$('#wallet-deposit');$('#copy-wallet-address').onclick=async()=>{if(owner!==identity())return;try{await navigator.clipboard.writeText(wallet);notify('Address copied');}catch{notify('Select the address to copy it');}};
  try{const p=await api('/api/portfolio/deposit');if(!host.isConnected||owner!==identity())return;if(p.wallet?.toLowerCase()!==key||p.chainId!==143)throw new Error('Wallet changed. Reopen Deposit.');qrCache.set(key,p.qr);if(qrCache.size>8)qrCache.delete(qrCache.keys().next().value);const frame=host.querySelector('.r-qr-frame');frame.innerHTML=`<img class="r-deposit-qr" src="${esc(p.qr)}" width="208" height="208" alt="Wallet address QR code">`;frame.setAttribute('aria-busy','false');}catch(e){if(host.isConnected)host.querySelector('.r-qr-error').textContent=e.message;}
 }
 async function send(){if(!S.boot.wallet){c.connect();return;}modal('Send','<div id="wallet-send"><p class="r-note">Loading your assets…</p></div>','r-wallet-modal');fitSheet();const host=$('#wallet-send'),owner=identity();try{let p=cached();let freshRead;if(!p||!(p.holdings||[]).some(h=>Number(h.amount)>0&&!h.staleBalance))p=await snapshot();else freshRead=snapshot();for(let attempt=0;attempt<12&&p.refreshing&&!(p.holdings||[]).some(h=>Number(h.amount)>0&&!h.staleBalance);attempt++){if(!host.isConnected||owner!==identity())return;await new Promise(r=>setTimeout(r,attempt?1000:350));p=await snapshot();}if(!host.isConnected||owner!==identity())return;const assets=(p.holdings||[]).filter(h=>Number(h.amount)>0&&!h.staleBalance);host.innerHTML=`<form id="wallet-send-form"><div class="r-wallet-form-body"><div class="r-send-asset"><div id="send-asset-logo"></div><label><span class="r-muted">Asset</span><select name="asset" aria-label="Asset">${assets.map(h=>`<option value="${esc(h.asset)}">${esc(h.token?.symbol||h.asset)}</option>`).join('')}</select></label><small id="send-available"></small></div><label class="r-field">Recipient<input name="recipient" placeholder="Wallet address · 0x…" autocomplete="off" spellcheck="false" pattern="0x[0-9a-fA-F]{40}" required></label><label class="r-field r-send-amount">Amount<input name="amount" inputmode="decimal" placeholder="0.00" autocomplete="off" required></label><div class="r-send-value"><span id="send-value">— USD</span><div><button type="button" data-send-fraction="25">25%</button><button type="button" data-send-fraction="50">50%</button></div></div><div class="r-send-fee"><span>Network</span><span class="r-wallet-network"><img src="/assets/MON.png" width="16" height="16" alt="">Monad · Fee in MON</span></div><p id="send-status" class="r-send-status" aria-live="polite"></p><p id="send-error" class="r-form-error" role="alert"></p></div><div class="r-wallet-footer"><button class="r-btn primary full" type="submit" ${assets.length?'':'disabled'}>Send</button></div></form>`;const form=$('#wallet-send-form');
 const submit=form.querySelector('[type=submit]');
 const selected=()=>assets.find(h=>h.asset===form.elements.asset.value);let paintedAsset;
 function update(){const h=selected(),t=h?.token||c.token(h?.asset);if(paintedAsset!==h?.asset){$('#send-asset-logo').innerHTML=h?logo(t):'';paintedAsset=h?.asset;}$('#send-available').textContent=h?'Available '+Number(h.amount).toLocaleString('en-US',{maximumSignificantDigits:8}):'No assets to send';const n=Number(form.elements.amount.value),price=Number(h?.valueUSD)/Number(h?.amount);$('#send-value').textContent=n>0&&h?.valueUSD!=null&&Number.isFinite(price)?usd(n*price):'— USD';const recipient=form.elements.recipient.value;submit.disabled=!h||!/^0x[0-9a-fA-F]{40}$/.test(recipient)||/^0x0{40}$/i.test(recipient)||recipient.toLowerCase()===S.boot.wallet.toLowerCase()||!/^(0|[1-9][0-9]*)(\.[0-9]+)?$/.test(form.elements.amount.value)||!Number.isFinite(n)||n<=0||n>Number(h.amount);}
 form.addEventListener('input',update);form.elements.asset.onchange=()=>{form.elements.amount.value='';update();};
 form.querySelectorAll('[data-send-fraction]').forEach(b=>b.onclick=()=>{const h=selected(),decimals=h?.asset==='MON'?18:h?.token?.decimals;if(!h||!Number.isInteger(decimals))return;const [whole,frac='']=String(h.amount).split('.'),raw=BigInt(whole+frac.padEnd(decimals,'0')),value=raw*BigInt(b.dataset.sendFraction)/100n,digits=value.toString().padStart(decimals+1,'0');form.elements.amount.value=decimals?digits.slice(0,-decimals)+'.'+digits.slice(-decimals).replace(/0+$/,''):digits;form.elements.amount.value=form.elements.amount.value.replace(/\.$/,'');update();});update();
 if(freshRead)(async()=>{for(let i=0;i<8;i++){const next=await(i? snapshot():freshRead);if(!host.isConnected||owner!==identity()||form.dataset.sent)return;if(!S.financialBusy&&!form.dataset.pending){const value=form.elements.asset.value,fresh=(next.holdings||[]).filter(h=>Number(h.amount)>0&&!h.staleBalance),list=next.refreshing?[...new Map([...assets,...fresh].map(h=>[h.asset,h])).values()]:fresh;assets.splice(0,assets.length,...list);const options=list.map(h=>`<option value="${esc(h.asset)}">${esc(h.token?.symbol||h.asset)}</option>`).join('');form.elements.asset.innerHTML=(list.some(h=>h.asset===value)?'':`<option value="${esc(value)}" disabled>Balance unavailable</option>`)+options;form.elements.asset.value=value;update();}if(!next.refreshing)return;await new Promise(r=>setTimeout(r,750));}})().catch(()=>{});
 form.onsubmit=async e=>{e.preventDefault();if(S.financialBusy||form.dataset.sent||form.dataset.pending)return;form.dataset.pending='1';const args={venue:'wallet',kind:'send',...Object.fromEntries(new FormData(form))};const button=form.querySelector('[type=submit]'),status=$('#send-status'),error=$('#send-error');button.disabled=true;form.querySelectorAll('input,select,button[data-send-fraction]').forEach(x=>x.disabled=true);let sent=false;try{const plan=await api('/api/execution/plan',args);verifySend(plan,args,assets);await c.submit(plan,{kind:'execution',validateTransaction:(tx,prep)=>verifySend({...plan,transaction:tx,approval:prep.approval},args,assets),current:()=>host.isConnected&&owner===identity(),done:()=>{},refresh:async()=>{const next=await api('/api/execution/plan',args);verifySend(next,args,assets);return next;},status:s=>{status.textContent=s;status.dataset.state='working';},submitted:(hash)=>{sent=true;form.dataset.sent='1';status.innerHTML=`Submitted · <a href="https://monadvision.com/tx/${esc(hash)}" target="_blank" rel="noopener noreferrer">View transaction</a>`;},recorded:hash=>{status.textContent='Confirming transfer…';S.portfolio=null;(async()=>{for(let i=0;i<25&&host.isConnected&&owner===identity();i++){try{const activity=await api('/api/activity'),entry=activity.entries.find(e=>e.tx?.toLowerCase()===hash.toLowerCase()),business=entry?.outcome?.businessState;if(entry?.state==='failed'||business==='reverted'){status.textContent='Transfer failed. Check Activity.';return;}if(entry?.state==='finalized'&&business==='sent'){status.textContent='Transfer complete';status.dataset.state='complete';button.textContent='Sent';return;}if(business==='transfer_unverified'){status.textContent='Checking token transfer · Activity';return;}}catch{}await new Promise(r=>setTimeout(r,1600));}if(host.isConnected)status.textContent='Submitted. Confirmation appears in Activity.';})().catch(()=>{});},uncertain:()=>{form.dataset.sent='1';error.textContent='Check this request in your wallet or Activity before sending again.';},error:message=>{error.textContent=message;status.dataset.state='error';}});}catch(e){error.textContent=e.message;}finally{if(!sent&&!form.dataset.sent)delete form.dataset.pending;button.disabled=sent||!!form.dataset.sent;form.querySelectorAll('input,select,button[data-send-fraction]').forEach(x=>x.disabled=sent||!!form.dataset.sent);}};}catch(e){if(host.isConnected)host.textContent=e.message;}}
 function verifySend(plan,args,assets){const h=assets.find(h=>h.asset===args.asset),t=h?.token||c.token(args.asset),decimals=args.asset==='MON'?18:t?.decimals;const match=/^(0|[1-9][0-9]*)(?:\.([0-9]+))?$/.exec(args.amount);if(!h||!Number.isInteger(decimals)||decimals<0||decimals>36||!match||(match[2]?.length||0)>decimals)throw new Error('Enter an amount with valid precision');const raw=BigInt(match[1]+(match[2]||'').padEnd(decimals,'0')),native=args.asset==='MON',to=native?args.recipient:t?.address;const expected=native?'0x':'0xa9059cbb'+args.recipient.slice(2).toLowerCase().padStart(64,'0')+raw.toString(16).padStart(64,'0');if(raw<=0n||plan.approval||plan.summary?.token!==args.asset||plan.summary?.recipient?.toLowerCase()!==args.recipient.toLowerCase()||plan.transaction?.to?.toLowerCase()!==to?.toLowerCase()||plan.transaction?.data?.toLowerCase()!==expected||BigInt(plan.transaction?.value||'0x0')!==(native?raw:0n))throw new Error('Transfer changed. Try again.');}
 return {profile,render,deposit,send};
}

export async function mountHolders(c,host,asset){
 if(!host||!/^0x[0-9a-fA-F]{40}$/.test(asset))return;
 host.innerHTML='<div class="r-holders-title"><h3>Holders</h3><small>Updating…</small></div>';
 for(let i=0;i<25&&host.isConnected;i++){
  try{const p=await c.api('/api/token-holders?asset='+encodeURIComponent(asset));if(!host.isConnected)return;
   if(!p.indexed){host.innerHTML='<div class="r-holders-title"><h3>Holders</h3></div><p class="r-note">Holder indexing is unavailable for this asset.</p>';return;}
   host.innerHTML=`<div class="r-holders-title"><h3>Holders ${p.total!=null?'<small>'+c.esc(p.total)+'</small>':''}</h3><small>${p.fetchedAt?c.esc(p.source)+' · '+c.age(p.fetchedAt)+(p.stale?' · Last known':''):p.refreshing?'Updating…':'Unavailable'}</small></div>${p.holders.map((h,i)=>`<a class="r-holder" href="https://monadvision.com/address/${c.esc(h.address)}" target="_blank" rel="noopener noreferrer"><span class="r-holder-rank">${i+1}</span><span><b>${c.esc(h.name&&!/^0x/i.test(h.name)?h.name:h.address.slice(0,6)+'…'+h.address.slice(-4))}</b><small>${c.esc(h.address.slice(0,6)+'…'+h.address.slice(-4))}</small></span><b>${Number(h.amount).toLocaleString('en-US',{maximumSignificantDigits:6})}</b></a>`).join('')}${!p.holders.length&&!p.refreshing?'<p class="r-note">'+c.esc(p.error||'No indexed holders yet.')+'</p>':''}`;
   if(!p.refreshing)return;
  }catch{if(host.isConnected)host.innerHTML='<h3>Holders</h3><p class="r-note">Temporarily unavailable.</p>';return;}
  await new Promise(r=>setTimeout(r,2000));
 }
}
