import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {ethers} from 'ethers';
import ganache from 'ganache';
const stage=new URL('..',import.meta.url).pathname;
const artifacts=JSON.parse(fs.readFileSync(stage+'/build/contracts.json')).contracts;
const network=ganache.provider({chain:{chainId:143,hardfork:'shanghai'},wallet:{totalAccounts:4},logging:{quiet:true}});
const provider=new ethers.BrowserProvider(network);provider.pollingInterval=10;
const deadline=async()=>BigInt((await network.request({method:'eth_getBlockByNumber',params:['latest',false]})).timestamp)+120n;
const [creator,buyer,stranger,creator2]=await Promise.all([0,1,2,3].map(i=>provider.getSigner(i)));
const address=await creator.getAddress(),buyerAddress=await buyer.getAddress();
let count=0;const ok=(v,msg)=>{assert(v,msg);count++;};
async function deploy(name,args=[],signer=creator){const a=artifacts[name];const c=await new ethers.ContractFactory(a.abi,a.bytecode,signer).deploy(...args);await c.waitForDeployment();return c;}
async function tx(p){return (await p).wait();}
async function revert(p,msg){try{await tx(p);}catch{count++;return;}throw Error('Expected revert: '+msg);}
const quote=await deploy('MockQuote'),dex=await deploy('MockFactory'),router=await deploy('MockRouter',[await dex.getAddress()]);
const factory=await deploy('RallyCommunityFactory',[await quote.getAddress(),await router.getAddress()]);
await tx(quote.mint(address,1_000_000_000n));await tx(quote.mint(buyerAddress,1_000_000_000n));
await tx(quote.approve(await factory.getAddress(),100_000_000n));
const launch=await tx(factory.launch('Community','COMM',100_000_000n,2000,5000,100,{gasLimit:8_000_000}));
const event=launch.logs.map(l=>{try{return factory.interface.parseLog(l);}catch{return null;}}).find(x=>x?.name==='CommunityLaunched');
ok(event.args.creator===address,'creator');
const token=new ethers.Contract(event.args.token,artifacts.RallyCommunityToken.abi,creator),vault=new ethers.Contract(event.args.vault,artifacts.RallyCommunityVault.abi,creator),pair=new ethers.Contract(event.args.pair,artifacts.MockPair.abi,creator);
ok(await factory.vaultOf(address)===await vault.getAddress(),'wallet vault');
ok(await token.totalSupply()===10n**27n,'fixed billion supply');
ok(await token.balanceOf(await pair.getAddress())===10n**27n,'all supply in pool');
ok(await token.balanceOf(address)===0n,'no creator tokens minted separately');
ok(await pair.balanceOf(address)>0n,'LP creator ownership');
ok(await quote.balanceOf(await pair.getAddress())===100_000_000n,'exact USDC seed');
ok(await quote.allowance(await factory.getAddress(),await router.getAddress())===0n,'seed allowance cleared');
ok(await token.allowance(await factory.getAddress(),await router.getAddress())===0n,'token allowance cleared');
ok(!token.interface.fragments.some(f=>f.name==='mint'),'no public mint');
await revert(factory.launch('Second','TWO',1_000_000n,0,0,100),'one launch per wallet');
await revert(vault.connect(stranger).setPolicy(2000,5000,100,10_000n,100_000_000n),'creator only');
await revert(vault.connect(stranger).autoExecute(),'only self');
await revert(vault.initializePair(await pair.getAddress()),'pair cannot change');
await revert(vault.setPolicy(10001,0,100,10_000n,100_000_000n),'bad buyback');
await revert(vault.setPolicy(0,10001,100,10_000n,100_000_000n),'bad burn');
await revert(vault.setPolicy(0,0,0,10_000n,100_000_000n),'zero protection');
await revert(vault.setPolicy(0,0,501,10_000n,100_000_000n),'max protection');
await revert(vault.setPolicy(0,0,100,1n,100_000_000n),'dust batch');
await tx(quote.connect(buyer).approve(await vault.getAddress(),1_000_000_000n));
const feed=ethers.id('feed');let n=0;const pay=(amount=10_000_000n,nonce=1n)=>vault.connect(buyer).pay(ethers.id('invoice-'+(++n)),feed,amount,nonce,{gasLimit:2_000_000});
const first=await tx(pay());
ok(await vault.grossRevenue()===10_000_000n,'gross settled revenue');
ok(await vault.creatorPaid()===8_000_000n,'80% creator');
ok(await vault.pendingBuyback()===2_000_000n,'20% reserve during warmup');
ok(await vault.tokensBurned()===0n,'no invented burn during warmup');
ok(await quote.balanceOf(await vault.getAddress())===await vault.pendingBuyback(),'reserve backed by USDC');
ok(first.logs.some(l=>{try{return vault.interface.parseLog(l)?.name==='RevenuePaid';}catch{return false;}}),'revenue event even buyback queued');
await revert(vault.connect(buyer).pay(ethers.id('invoice-1'),feed,10_000_000n,1n),'invoice replay');
await revert(pay(10_000_000n,2n),'wrong policy nonce');
await revert(vault.executeBuyback(0),'expired deadline');
await network.request({method:'evm_increaseTime',params:[601]});await network.request({method:'evm_mine',params:[]});
const beforeSupply=await token.totalSupply();await tx(vault.connect(stranger).executeBuyback(await deadline(),{gasLimit:2_000_000}));
ok(await vault.quoteSpent()===500_000n,'0.5% pool input cap');
ok(await vault.pendingBuyback()===1_500_000n,'partial drain retained');
ok(await vault.tokensBought()>0n,'received tokens');
ok(await vault.tokensBurned()===await vault.tokensBought()/2n,'50% burn');
ok(beforeSupply-await token.totalSupply()===await vault.tokensBurned(),'supply actually destroyed');
ok(await token.balanceOf(address)===await vault.tokensBought()-await vault.tokensBurned(),'unburned bought tokens to creator');
ok(await quote.allowance(await vault.getAddress(),await router.getAddress())===0n,'buyback allowance reset');
await tx(vault.setPaused(true));const queued=await vault.pendingBuyback();await tx(pay());ok(await vault.pendingBuyback()===queued+2_000_000n,'paused still pays and reserves');
await revert(vault.connect(stranger).setPaused(false),'pause owner only');
await tx(vault.setPaused(false));await tx(router.setFail(true));const spent=await vault.quoteSpent();await tx(pay());ok(await vault.quoteSpent()===spent,'swap revert isolated from payment');
ok(await quote.balanceOf(await vault.getAddress())===await vault.pendingBuyback(),'failed swap reserve intact');
await tx(router.setFail(false));await tx(vault.setPolicy(0,10000,100,10_000n,100_000_000n));
await revert(pay(10_000_000n,1n),'old checkout after policy change');
await tx(vault.setPaused(true));const creatorBefore=await quote.balanceOf(address),pendingBefore=await vault.pendingBuyback();await tx(pay(10_000_000n,2n));
ok(await quote.balanceOf(address)-creatorBefore===10_000_000n,'zero buyback direct full creator');ok(await vault.pendingBuyback()===pendingBefore,'old reserves preserved');
ok(!vault.interface.fragments.some(f=>['withdraw','sweep','rescue'].includes(f.name)),'no reserve sweep');
await tx(vault.setPolicy(10000,10000,100,10_000n,100_000_000n));const cBefore=await quote.balanceOf(address);await tx(pay(10_000_000n,3n));ok(await quote.balanceOf(address)===cBefore,'100% reserve');
await tx(vault.setPaused(false));await network.request({method:'evm_increaseTime',params:[601]});await network.request({method:'evm_mine',params:[]});
const supplyBefore=await token.totalSupply(),burnBefore=await vault.tokensBurned();await tx(vault.executeBuyback(await deadline(),{gasLimit:2_000_000}));
ok(supplyBefore-await token.totalSupply()===await vault.tokensBurned()-burnBefore,'100% actual burn');
const other=await creator2.getAddress();await tx(quote.mint(other,1_000_000n));await tx(quote.connect(creator2).approve(await factory.getAddress(),1_000_000n));await tx(factory.connect(creator2).launch('Other','OTHER',1_000_000n,10000,10000,100,{gasLimit:8_000_000}));
const otherVault=new ethers.Contract(await factory.vaultOf(other),artifacts.RallyCommunityVault.abi,buyer);await tx(quote.connect(buyer).approve(await otherVault.getAddress(),10_000_000n));await tx(otherVault.pay(ethers.id('thin'),feed,10_000_000n,1n,{gasLimit:2_000_000}));await network.request({method:'evm_increaseTime',params:[601]});await network.request({method:'evm_mine',params:[]});
await revert(otherVault.executeBuyback(await deadline(),{gasLimit:2_000_000}),'thin liquidity below batch minimum');ok(await otherVault.pendingBuyback()===10_000_000n,'thin pool queues');
// A current quote below the time-weighted floor must not consume the reserve.
await tx(quote.mint(await pair.getAddress(),100_000_000n));await tx(pair.sync());
const protectedSpent=await vault.quoteSpent(),protectedPending=await vault.pendingBuyback();
await tx(pay(10_000_000n,3n));ok(await vault.quoteSpent()===protectedSpent,'price deviation queues automatic buyback');ok(await vault.pendingBuyback()===protectedPending+10_000_000n,'protected reserve remains backed');
await revert(vault.executeBuyback(await deadline(),{gasLimit:2_000_000}),'TWAP price floor');
await tx(vault.setPolicy(10000,0,500,10_000n,100_000_000n));await tx(vault.checkpoint());await network.request({method:'evm_increaseTime',params:[601]});await network.request({method:'evm_mine',params:[]});
const treasuryBefore=await token.balanceOf(address),zeroBurnSupply=await token.totalSupply();await tx(vault.executeBuyback(await deadline(),{gasLimit:2_000_000}));
ok(await token.totalSupply()===zeroBurnSupply,'zero burn preserves supply');ok(await token.balanceOf(address)>treasuryBefore,'zero burn sends bought tokens to treasury');
await network.disconnect();
const result={ok:true,checks:count,sourceHash:crypto.createHash('sha256').update(fs.readFileSync(stage+'/contracts/RallyCommunity.sol')).digest('hex'),environment:'isolated EVM chain 143 with explicit mock USDC/router/pair; no mainnet transactions',launchGas:launch.gasUsed.toString()};
fs.writeFileSync(stage+'/build/community-tests.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
