pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google(); mavenCentral()
        maven {
            url 'https://jitpack.io'
            content {
                includeGroupByRegex 'com\\.github\\.komputing(\\..*)?'
                includeGroup 'com.walletconnect.Scarlet'
                includeGroup 'com.github.multiformats'
            }
        }
    }
}
rootProject.name = 'RallyAndroid'
include ':app', ':baselineprofile'
